version: '3'
services:
  web:
    build:
      context: ./docker/web
    container_name: 'docker_boilerplate_web'
    restart: unless-stopped
    volumes:
      - ./www/:/var/www/html
      - ./config/php/php.ini:/etc/php/conf.d/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2      
    ports:
      - "8889:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
    container_name: 'docker_boilerplate_database'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    volumes: 
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3389:3306"
    networks:
      - app-network

networks:
  app-network:
